driver:
    name: vagrant
    network:
    - ["private_network", { type: "dhcp" }]
    customize:
        memory: 2048

provisioner:
    name: chef_solo
    legacy_mode: true
    require_chef_omnibus: 13.3.42
    data_bags_path: ./data_bags
    roles_path: ./roles
    environments_path: ./environments
    solo_rb:
        environment: dev

verifier:
  name: inspec

platforms:
  - name: debian/9.3
    driver:
      box_url: https://vagrantcloud.com/generic/boxes/debian9/versions/1.8.14/providers/virtualbox.box
      box: generic/debian9
    driver_config:
      vm_hostname: chef-server

suites:
  - name: chef-server
    run_list:
      - role[chef-server]
    verifier:
      inspec_tests:
        - ./cookbooks/chef-server/test
